name: Daily CVE Pull and Post to Teams

on:
  schedule:
    - cron: "6 17 * * *" # UTC 11:30 AM → 5:00 PM IST
  workflow_dispatch:
jobs:
  run-cve-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run CVE Pull Script
        env:
          CLASSIC_TOKEN_GITHUB: ${{ secrets.CLASSIC_TOKEN_GITHUB }}
          CVE_GITHUB_API_URL: ${{ secrets.CVE_GITHUB_API_URL }}
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
          TEAMS_FLOW_URL: ${{ secrets.TEAMS_FLOW_URL }}
        run: python cve_pull/teams_channel.py
